GET https://api.travis-ci.org/repo/409371/branches?limit=10&offset=20 HTTP/1.1
Accept: application/json
Travis-API-Version: 3

HTTP/1.1 200 OK
Content-Type: application/json

{
  "@type": "branches",
  "@href": "/repo/409371/branches?limit=10&offset=20",
  "@representation": "standard",
  "@pagination": {
    "limit": 10,
    "offset": 20,
    "count": 22,
    "is_first": false,
    "is_last": true,
    "next": null,
    "prev": {
      "@href": "/repo/409371/branches?limit=10&offset=10",
      "offset": 10,
      "limit": 10
    },
    "first": {
      "@href": "/repo/409371/branches?limit=10&offset=0",
      "offset": 0,
      "limit": 10
    },
    "last": {
      "@href": "/repo/409371/branches?limit=10&offset=20",
      "offset": 20,
      "limit": 10
    }
  },
  "branches": [
    {
      "@type": "branch",
      "@href": "/repo/409371/branch/v1.7.7",
      "@representation": "standard",
      "name": "v1.7.7",
      "repository": {
        "@type": "repository",
        "@href": "/repo/409371",
        "@representation": "minimal",
        "id": 409371,
        "name": "travis.rb",
        "slug": "travis-ci/travis.rb"
      },
      "default_branch": false,
      "exists_on_github": false,
      "last_build": {
        "@type": "build",
        "@href": "/build/64086905",
        "@representation": "minimal",
        "id": 64086905,
        "number": "685",
        "state": "passed",
        "duration": 360,
        "event_type": "push",
        "previous_state": null,
        "pull_request_title": null,
        "pull_request_number": null,
        "started_at": "2015-05-26T12:52:46Z",
        "finished_at": "2015-05-26T12:54:55Z"
      }
    },
    {
      "@type": "branch",
      "@href": "/repo/409371/branch/v1.7.6",
      "@representation": "standard",
      "name": "v1.7.6",
      "repository": {
        "@type": "repository",
        "@href": "/repo/409371",
        "@representation": "minimal",
        "id": 409371,
        "name": "travis.rb",
        "slug": "travis-ci/travis.rb"
      },
      "default_branch": false,
      "exists_on_github": false,
      "last_build": {
        "@type": "build",
        "@href": "/build/57651617",
        "@representation": "minimal",
        "id": 57651617,
        "number": "679",
        "state": "passed",
        "duration": 669,
        "event_type": "push",
        "previous_state": null,
        "pull_request_title": null,
        "pull_request_number": null,
        "started_at": "2015-04-08T14:28:31Z",
        "finished_at": "2015-04-08T14:34:03Z"
      }
    }
  ]
}
